from typing import Any

ROOT_KEY_NAME: str
SWIG_PYTHON_LEGACY_BOOL: int
reg_binary: int
reg_dword: int
reg_sz: int
reg_unknown: int

def reg_data_type(name, subkey=...) -> regval_type_t: ...
def reg_delete(name, subkey=...) -> bool: ...
def reg_delete_subkey(name) -> bool: ...
def reg_delete_tree(name) -> bool: ...
def reg_exists(name, subkey=...) -> bool: ...
def reg_flush() -> Any: ...
def reg_load() -> Any: ...
def reg_read_binary(*args, **kwargs): ...
def reg_read_bool(name, defval, subkey=...) -> bool: ...
def reg_read_int(name, defval, subkey=...) -> int: ...
def reg_read_string(*args, **kwargs): ...
def reg_read_strlist(subkey) -> Any: ...
def reg_subkey_exists(name) -> bool: ...
def reg_subkey_subkeys(*args, **kwargs): ...
def reg_subkey_values(*args, **kwargs): ...
def reg_update_filestrlist(subkey, add, maxrecs, rem=...) -> Any: ...
def reg_update_strlist(subkey, add, maxrecs, rem=..., ignorecase=...) -> Any: ...
def reg_write_binary(*args, **kwargs): ...
def reg_write_bool(name, value, subkey=...) -> Any: ...
def reg_write_int(name, value, subkey=...) -> Any: ...
def reg_write_string(name, utf8, subkey=...) -> Any: ...
def set_registry_root(name) -> bool: ...
# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"