# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from typing import overload

SWIG_PYTHON_LEGACY_BOOL: int

def add_refinfo_dref(insn, _from, ri, opval, type, opoff) -> ea_t: ...
def calc_basevalue(target, base) -> ea_t: ...
def calc_offset_base(ea, n) -> ea_t: ...
def calc_probable_base_by_value(ea, off) -> ea_t: ...
def calc_reference_data(target, base, _from, ri, opval) -> bool: ...
@overload
def calc_target(_from, opval, ri) -> ea_t: ...
@overload
def calc_target(_from, ea, n, opval) -> ea_t: ...
def can_be_off32(ea) -> ea_t: ...
def get_default_reftype(ea) -> reftype_t: ...
def get_offbase(ea, n) -> ea_t: ...
def get_offset_expr(ea, n, ri, _from, offset, getn_flags=...) -> int: ...
def get_offset_expression(ea, n, _from, offset, getn_flags=...) -> int: ...
def op_offset(ea, n, type_and_flags, target=..., base=..., tdelta=...) -> bool: ...
def op_offset_ex(ea, n, ri) -> bool: ...
def op_plain_offset(ea, n, base) -> bool: ...
