# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

SRCLANG_C: int
SRCLANG_CPP: int
SRCLANG_GO: int
SRCLANG_OBJC: int
SRCLANG_SWIFT: int
SWIG_PYTHON_LEGACY_BOOL: int

def parse_decls_for_srclang(lang, til, input, is_path) -> int: ...
def parse_decls_with_parser(parser_name, til, input, is_path) -> int: ...
def select_parser_by_name(name) -> bool: ...
def select_parser_by_srclang(lang) -> bool: ...
def set_parser_argv(parser_name, argv) -> int: ...
