# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from _typeshed import Incomplete

def moduleMember(module, name): ...

class Literal:
    string: Incomplete
    def __init__(self, string) -> None: ...
    def __str__(self) -> str: ...
    def __or__(self, r_op): ...
