# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from .misc import Literal as Literal, moduleMember as moduleMember

class ProxyMetaclass(type):
    def __init__(*args) -> None: ...
    def __getattribute__(cls, name): ...
    def __str__(cls) -> str: ...
    def __or__(self, r_op): ...
    def __eq__(self, other): ...
