# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from _typeshed import Incomplete

def _swig_repr(self): ...
def _swig_setattr_nondynamic_instance_variable(set): ...
def _swig_setattr_nondynamic_class_variable(set): ...
def _swig_add_metaclass(metaclass): ...

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

SWIG_PYTHON_LEGACY_BOOL: Incomplete

class bitrange_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    def __init__(self, *args) -> None: ...
    def init(self, *args) -> None: ...
    def reset(self, *args) -> None: ...
    def empty(self, *args) -> bool: ...
    def bitoff(self, *args) -> uint: ...
    def bitsize(self, *args) -> uint: ...
    def bytesize(self, *args) -> uint: ...
    def mask64(self, *args) -> uint64: ...
    def has_common(self, *args) -> bool: ...
    def apply_mask(self, *args) -> bool: ...
    def intersect(self, *args) -> None: ...
    def create_union(self, *args) -> None: ...
    def sub(self, *args) -> bool: ...
    def shift_down(self, *args) -> None: ...
    def shift_up(self, *args) -> None: ...
    def extract(self, *args) -> bool: ...
    def inject(self, *args) -> bool: ...
    def __eq__(self, *args) -> bool: ...
    def __ne__(self, *args) -> bool: ...
    def __lt__(self, *args) -> bool: ...
    def __gt__(self, *args) -> bool: ...
    def __le__(self, *args) -> bool: ...
    def __ge__(self, *args) -> bool: ...
    def compare(self, *args) -> int: ...
    def __str__(self, *args) -> qstring: ...
    __swig_destroy__: Incomplete
