# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from _typeshed import Incomplete

def _swig_repr(self): ...
def _swig_setattr_nondynamic_instance_variable(set): ...
def _swig_setattr_nondynamic_class_variable(set): ...
def _swig_add_metaclass(metaclass): ...

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

SWIG_PYTHON_LEGACY_BOOL: Incomplete

def get_auto_state(*args) -> atype_t: ...
def set_auto_state(*args) -> atype_t: ...

class auto_display_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    type: Incomplete
    ea: Incomplete
    state: Incomplete
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete

cvar: Incomplete
AU_NONE: Incomplete
AU_UNK: Incomplete
AU_CODE: Incomplete
AU_WEAK: Incomplete
AU_PROC: Incomplete
AU_TAIL: Incomplete
AU_FCHUNK: Incomplete
AU_USED: Incomplete
AU_USD2: Incomplete
AU_TYPE: Incomplete
AU_LIBF: Incomplete
AU_LBF2: Incomplete
AU_LBF3: Incomplete
AU_CHLB: Incomplete
AU_FINAL: Incomplete
st_Ready: Incomplete
st_Think: Incomplete
st_Waiting: Incomplete
st_Work: Incomplete

def get_auto_display(*args) -> bool: ...
def show_auto(*args) -> None: ...
def show_addr(*args) -> None: ...
def set_ida_state(*args) -> idastate_t: ...
def may_create_stkvars(*args) -> bool: ...
def may_trace_sp(*args) -> bool: ...
def auto_mark_range(*args) -> None: ...
def auto_mark(*args) -> None: ...
def auto_unmark(*args) -> None: ...
def plan_ea(*args) -> None: ...
def plan_range(*args) -> None: ...
def auto_make_code(*args) -> None: ...
def auto_make_proc(*args) -> None: ...
def auto_postpone_analysis(*args) -> bool: ...
def reanalyze_callers(*args) -> None: ...
def revert_ida_decisions(*args) -> None: ...
def auto_apply_type(*args) -> None: ...
def auto_apply_tail(*args) -> None: ...
def plan_and_wait(*args) -> int: ...
def auto_wait(*args) -> bool: ...
def auto_wait_range(*args) -> ssize_t: ...
def auto_make_step(*args) -> bool: ...
def auto_cancel(*args) -> None: ...
def auto_is_ok(*args) -> bool: ...
def peek_auto_queue(*args) -> ea_t: ...
def auto_get(*args) -> ea_t: ...
def auto_recreate_insn(*args) -> int: ...
def is_auto_enabled(*args) -> bool: ...
def enable_auto(*args) -> bool: ...
