# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from _typeshed import Incomplete

def _swig_repr(self): ...
def _swig_setattr_nondynamic_instance_variable(set): ...
def _swig_setattr_nondynamic_class_variable(set): ...
def _swig_add_metaclass(metaclass): ...

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

SWIG_PYTHON_LEGACY_BOOL: Incomplete

def get_entry_qty(*args) -> size_t: ...

AEF_UTF8: Incomplete
AEF_IDBENC: Incomplete
AEF_NODUMMY: Incomplete

def add_entry(*args) -> bool: ...
def get_entry_ordinal(*args) -> uval_t: ...
def get_entry(*args) -> ea_t: ...
def get_entry_name(*args) -> 'qstring *': ...
def rename_entry(*args) -> bool: ...
def set_entry_forwarder(*args) -> bool: ...
def get_entry_forwarder(*args) -> 'qstring *': ...
