# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from _typeshed import Incomplete

def _swig_repr(self): ...
def _swig_setattr_nondynamic_instance_variable(set): ...
def _swig_setattr_nondynamic_class_variable(set): ...
def _swig_add_metaclass(metaclass): ...

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

SWIG_PYTHON_LEGACY_BOOL: Incomplete

class qfile_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    __idc_cvt_id__: Incomplete
    def __init__(self, *args) -> None: ...
    def opened(self, *args) -> bool: ...
    def close(self, *args) -> None: ...
    __swig_destroy__: Incomplete
    def open(self, *args) -> bool: ...
    @staticmethod
    def from_fp(*args) -> 'qfile_t *': ...
    @staticmethod
    def from_capsule(*args) -> 'qfile_t *': ...
    @staticmethod
    def tmpfile(*args) -> 'qfile_t *': ...
    def get_fp(self, *args) -> 'FILE *': ...
    def seek(self, *args) -> int: ...
    def tell(self, *args) -> int64: ...
    def readbytes(self, *args) -> 'PyObject *': ...
    def read(self, *args) -> 'PyObject *': ...
    def gets(self, *args) -> 'PyObject *': ...
    def writebytes(self, *args) -> int: ...
    def write(self, *args) -> int: ...
    def puts(self, *args) -> int: ...
    def size(self, *args) -> int64: ...
    def flush(self, *args) -> int: ...
    def filename(self, *args) -> 'PyObject *': ...
    def get_byte(self, *args) -> 'PyObject *': ...
    def put_byte(self, *args) -> int: ...

def qfile_t_from_fp(*args) -> 'qfile_t *': ...
def qfile_t_from_capsule(*args) -> 'qfile_t *': ...
def qfile_t_tmpfile(*args) -> 'qfile_t *': ...
