# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

import ida_idaapi
from _typeshed import Incomplete

def _swig_repr(self): ...
def _swig_setattr_nondynamic_instance_variable(set): ...
def _swig_setattr_nondynamic_class_variable(set): ...
def _swig_add_metaclass(metaclass): ...

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

SWIG_PYTHON_LEGACY_BOOL: Incomplete

class dyn_member_ref_array:
    thisown: Incomplete
    __repr__ = _swig_repr
    data: Incomplete
    count: Incomplete
    def __init__(self, *args) -> None: ...
    def __len__(self, *args) -> size_t: ...
    def __getitem__(self, *args) -> 'member_t const &': ...
    def __setitem__(self, *args) -> None: ...
    __iter__ = ida_idaapi._bounded_getitem_iterator
    __swig_destroy__: Incomplete

STRUC_SEPARATOR: Incomplete

class member_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    id: Incomplete
    soff: Incomplete
    eoff: Incomplete
    flag: Incomplete
    props: Incomplete
    def unimem(self, *args) -> bool: ...
    def has_union(self, *args) -> bool: ...
    def by_til(self, *args) -> bool: ...
    def has_ti(self, *args) -> bool: ...
    def is_baseclass(self, *args) -> bool: ...
    def is_dupname(self, *args) -> bool: ...
    def is_destructor(self, *args) -> bool: ...
    def get_soff(self, *args) -> ea_t: ...
    def get_size(self, *args) -> asize_t: ...
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete

MF_OK: Incomplete
MF_UNIMEM: Incomplete
MF_HASUNI: Incomplete
MF_BYTIL: Incomplete
MF_HASTI: Incomplete
MF_BASECLASS: Incomplete
MF_DTOR: Incomplete
MF_DUPNAME: Incomplete

class struc_t:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __repr__ = _swig_repr
    id: Incomplete
    memqty: Incomplete
    members: Incomplete
    age: Incomplete
    props: Incomplete
    def is_varstr(self, *args) -> bool: ...
    def is_union(self, *args) -> bool: ...
    def has_union(self, *args) -> bool: ...
    def like_union(self, *args) -> bool: ...
    def is_choosable(self, *args) -> bool: ...
    def from_til(self, *args) -> bool: ...
    def is_hidden(self, *args) -> bool: ...
    def is_frame(self, *args) -> bool: ...
    def get_alignment(self, *args) -> int: ...
    def is_ghost(self, *args) -> bool: ...
    def is_synced(self, *args) -> bool: ...
    def is_mappedto(self, *args) -> bool: ...
    def is_copyof(self, *args) -> bool: ...
    def set_alignment(self, *args) -> None: ...
    def get_last_member(self, *args) -> 'member_t const *': ...
    ordinal: Incomplete
    def __get_members__(self, *args) -> 'dynamic_wrapped_array_t< member_t >': ...
    def get_member(self, index): ...
    __swig_destroy__: Incomplete

SF_VAR: Incomplete
SF_UNION: Incomplete
SF_HASUNI: Incomplete
SF_NOLIST: Incomplete
SF_TYPLIB: Incomplete
SF_HIDDEN: Incomplete
SF_FRAME: Incomplete
SF_ALIGN: Incomplete
SF_GHOST: Incomplete
SF_ASMTIL: Incomplete

def get_struc_qty(*args) -> size_t: ...
def get_first_struc_idx(*args) -> uval_t: ...
def get_last_struc_idx(*args) -> uval_t: ...
def get_prev_struc_idx(*args) -> uval_t: ...
def get_next_struc_idx(*args) -> uval_t: ...
def get_struc_idx(*args) -> uval_t: ...
def get_struc_by_idx(*args) -> tid_t: ...
def get_struc(*args) -> 'struc_t *': ...
def get_struc_id(*args) -> tid_t: ...
def get_struc_name(*args) -> 'qstring *': ...

STRNFL_REGEX: Incomplete

def get_struc_cmt(*args) -> 'qstring *': ...
def get_struc_size(*args) -> asize_t: ...
def get_struc_prev_offset(*args) -> ea_t: ...
def get_struc_next_offset(*args) -> ea_t: ...
def get_struc_last_offset(*args) -> ea_t: ...
def get_struc_first_offset(*args) -> ea_t: ...
def unsync_and_delete_struc(*args) -> None: ...
def get_max_offset(*args) -> ea_t: ...
def is_varstr(*args) -> bool: ...
def is_union(*args) -> bool: ...
def get_member_struc(*args) -> 'struc_t *': ...
def get_sptr(*args) -> 'struc_t *': ...
def get_member(*args) -> 'member_t *': ...
def get_member_id(*args) -> tid_t: ...
def get_member_by_name(*args) -> 'member_t *': ...
def get_member_by_fullname(*args) -> 'struc_t **': ...
def get_member_fullname(*args) -> 'qstring *': ...
def get_member_name(*args) -> 'qstring *': ...
def get_member_cmt(*args) -> 'qstring *': ...
def get_member_size(*args) -> asize_t: ...
def is_varmember(*args) -> bool: ...
def get_best_fit_member(*args) -> 'member_t *': ...
def get_next_member_idx(*args) -> ssize_t: ...
def get_prev_member_idx(*args) -> ssize_t: ...
def add_struc(*args) -> tid_t: ...
def del_struc(*args) -> bool: ...
def set_struc_idx(*args) -> bool: ...
def set_struc_align(*args) -> bool: ...
def set_struc_name(*args) -> bool: ...
def set_struc_cmt(*args) -> bool: ...

STRUC_ERROR_MEMBER_OK: Incomplete
STRUC_ERROR_MEMBER_NAME: Incomplete
STRUC_ERROR_MEMBER_OFFSET: Incomplete
STRUC_ERROR_MEMBER_SIZE: Incomplete
STRUC_ERROR_MEMBER_TINFO: Incomplete
STRUC_ERROR_MEMBER_STRUCT: Incomplete
STRUC_ERROR_MEMBER_UNIVAR: Incomplete
STRUC_ERROR_MEMBER_VARLAST: Incomplete
STRUC_ERROR_MEMBER_NESTED: Incomplete
STRUC_ERROR_MEMBER_LTUDT: Incomplete

def add_struc_member(*args) -> struc_error_t: ...
def del_struc_member(*args) -> bool: ...
def del_struc_members(*args) -> int: ...
def set_member_name(*args) -> bool: ...
def set_member_type(*args) -> bool: ...
def set_member_cmt(*args) -> bool: ...
def expand_struc(*args) -> bool: ...
def save_struc(*args) -> None: ...
def set_struc_hidden(*args) -> None: ...
def set_struc_listed(*args) -> None: ...

SMT_BADARG: Incomplete
SMT_NOCOMPAT: Incomplete
SMT_WORSE: Incomplete
SMT_SIZE: Incomplete
SMT_ARRAY: Incomplete
SMT_OVERLAP: Incomplete
SMT_FAILED: Incomplete
SMT_OK: Incomplete
SMT_KEEP: Incomplete

def get_member_tinfo(*args) -> bool: ...
def del_member_tinfo(*args) -> bool: ...
def set_member_tinfo(*args) -> smt_code_t: ...

SET_MEMTI_MAY_DESTROY: Incomplete
SET_MEMTI_COMPATIBLE: Incomplete
SET_MEMTI_FUNCARG: Incomplete
SET_MEMTI_BYTIL: Incomplete
SET_MEMTI_USERTI: Incomplete

def get_or_guess_member_tinfo(*args) -> bool: ...
def retrieve_member_info(*args) -> 'opinfo_t *': ...
def is_anonymous_member_name(*args) -> bool: ...
def is_dummy_member_name(*args) -> bool: ...
def get_member_by_id(*args) -> 'qstring *, struc_t **': ...
def is_member_id(*args) -> bool: ...
def is_special_member(*args) -> bool: ...

class udm_visitor_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    def visit_udm(self, *args) -> int: ...
    __swig_destroy__: Incomplete
    def __init__(self, *args) -> None: ...
    def __disown__(self): ...

def visit_stroff_udms(*args) -> 'adiff_t *': ...
def stroff_as_size(*args) -> bool: ...

class struct_field_visitor_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    def visit_field(self, *args) -> int: ...
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete
    def __disown__(self): ...

def visit_stroff_fields(*args) -> 'adiff_t *': ...
def get_innermost_member(*args) -> 'PyObject *': ...
