# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from _typeshed import Incomplete

def _swig_repr(self): ...
def _swig_setattr_nondynamic_instance_variable(set): ...
def _swig_setattr_nondynamic_class_variable(set): ...
def _swig_add_metaclass(metaclass): ...

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

SWIG_PYTHON_LEGACY_BOOL: Incomplete
SEARCH_UNICODE: int
SEARCH_UP: Incomplete
SEARCH_DOWN: Incomplete
SEARCH_NEXT: Incomplete
SEARCH_CASE: Incomplete
SEARCH_REGEX: Incomplete
SEARCH_NOBRK: Incomplete
SEARCH_NOSHOW: Incomplete
SEARCH_IDENT: Incomplete
SEARCH_BRK: Incomplete
SEARCH_USE: Incomplete
SEARCH_DEF: Incomplete
SEARCH_USESEL: Incomplete

def search_down(*args) -> bool: ...
def find_error(*args) -> 'int *': ...
def find_notype(*args) -> 'int *': ...
def find_unknown(*args) -> ea_t: ...
def find_defined(*args) -> ea_t: ...
def find_suspop(*args) -> 'int *': ...
def find_data(*args) -> ea_t: ...
def find_code(*args) -> ea_t: ...
def find_not_func(*args) -> ea_t: ...
def find_imm(*args) -> 'int *': ...
def find_text(*args) -> ea_t: ...
def find_reg_access(*args) -> ea_t: ...
def find_binary(*args) -> ea_t: ...
