# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from _typeshed import Incomplete

def _swig_repr(self): ...
def _swig_setattr_nondynamic_instance_variable(set): ...
def _swig_setattr_nondynamic_class_variable(set): ...
def _swig_add_metaclass(metaclass): ...

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

SWIG_PYTHON_LEGACY_BOOL: Incomplete
SRCLANG_C: Incomplete
SRCLANG_CPP: Incomplete
SRCLANG_OBJC: Incomplete
SRCLANG_SWIFT: Incomplete
SRCLANG_GO: Incomplete

def select_parser_by_name(*args) -> bool: ...
def select_parser_by_srclang(*args) -> bool: ...
def set_parser_argv(*args) -> int: ...
def parse_decls_for_srclang(*args) -> int: ...
def parse_decls_with_parser(*args) -> int: ...
