# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from _typeshed import Incomplete

def _swig_repr(self): ...
def _swig_setattr_nondynamic_instance_variable(set): ...
def _swig_setattr_nondynamic_class_variable(set): ...
def _swig_add_metaclass(metaclass): ...

class _SwigNonDynamicMeta(type):
    __setattr__: Incomplete

SWIG_PYTHON_LEGACY_BOOL: Incomplete

def idadir(*args) -> 'char const *': ...
def getsysfile(*args) -> 'char const *': ...

CFG_SUBDIR: Incomplete
IDC_SUBDIR: Incomplete
IDS_SUBDIR: Incomplete
IDP_SUBDIR: Incomplete
LDR_SUBDIR: Incomplete
SIG_SUBDIR: Incomplete
TIL_SUBDIR: Incomplete
PLG_SUBDIR: Incomplete
THM_SUBDIR: Incomplete

def get_user_idadir(*args) -> 'char const *': ...
def get_ida_subdirs(*args) -> 'qstrvec_t *': ...

IDA_SUBDIR_IDP: Incomplete
IDA_SUBDIR_IDADIR_FIRST: Incomplete
IDA_SUBDIR_ONLY_EXISTING: Incomplete

def get_special_folder(*args) -> size_t: ...

CSIDL_APPDATA: Incomplete
CSIDL_LOCAL_APPDATA: Incomplete
CSIDL_PROGRAM_FILES: Incomplete
CSIDL_PROGRAM_FILES_COMMON: Incomplete
CSIDL_PROGRAM_FILESX86: Incomplete

class file_enumerator_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    def visit_file(self, *args) -> int: ...
    __swig_destroy__: Incomplete
    def __init__(self, *args) -> None: ...
    def __disown__(self): ...

def enumerate_files2(*args) -> int: ...
def fopenWT(*args) -> 'FILE *': ...
def fopenWB(*args) -> 'FILE *': ...
def fopenRT(*args) -> 'FILE *': ...
def fopenRB(*args) -> 'FILE *': ...
def fopenM(*args) -> 'FILE *': ...
def fopenA(*args) -> 'FILE *': ...

class ioports_fallback_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    def handle(self, *args) -> bool: ...
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete
    def __disown__(self): ...

def read_ioports2(*args) -> ssize_t: ...

class choose_ioport_parser_t:
    thisown: Incomplete
    __repr__ = _swig_repr
    def parse(self, *args) -> bool: ...
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Incomplete
    def __disown__(self): ...

def choose_ioport_device2(*args) -> bool: ...

LINPUT_NONE: Incomplete
LINPUT_LOCAL: Incomplete
LINPUT_RFILE: Incomplete
LINPUT_PROCMEM: Incomplete
LINPUT_GENERIC: Incomplete

def qlgetz(*args) -> size_t: ...
def open_linput(*args) -> 'linput_t *': ...

class generic_linput_t:
    thisown: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    __repr__ = _swig_repr
    filesize: Incomplete
    blocksize: Incomplete
    def read(self, *args) -> ssize_t: ...
    __swig_destroy__: Incomplete

def create_generic_linput(*args) -> 'linput_t *': ...
def create_memory_linput(*args) -> 'linput_t *': ...
def get_linput_type(*args) -> linput_type_t: ...
def eclose(*args) -> None: ...
def enumerate_files(*args) -> 'PyObject *': ...
def create_bytearray_linput(*args) -> 'linput_t *': ...
def close_linput(*args) -> None: ...
