# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from .objcreator import widgetPluginPath as widgetPluginPath
from _typeshed import Incomplete

__all__ = ['compileUi', 'compileUiDir', 'loadUiType', 'loadUi', 'widgetPluginPath']

def compileUiDir(dir, recurse: bool = False, map: Incomplete | None = None, **compileUi_args) -> None: ...
def compileUi(uifile, pyfile, execute: bool = False, indent: int = 4, from_imports: bool = False, resource_suffix: str = '_rc', import_from: str = '.') -> None: ...
def loadUiType(uifile, from_imports: bool = False, resource_suffix: str = '_rc', import_from: str = '.'): ...
def loadUi(uifile, baseinstance: Incomplete | None = None, package: str = '', resource_suffix: str = '_rc'): ...
