# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from .exceptions import NoSuchWidgetError as NoSuchWidgetError, WidgetPluginError as WidgetPluginError
from _typeshed import Incomplete

widgetPluginPath: Incomplete
MATCH: bool
NO_MATCH: bool
MODULE: int
CW_FILTER: int

class QObjectCreator:
    _cpolicy: Incomplete
    _cwFilters: Incomplete
    _modules: Incomplete
    _customWidgets: Incomplete
    def __init__(self, creatorPolicy) -> None: ...
    def createQObject(self, classname, *args, **kwargs): ...
    def invoke(self, rname, method, args=()): ...
    def findQObjectType(self, classname): ...
    def getSlot(self, obj, slotname): ...
    def asString(self, s): ...
    def addCustomWidget(self, widgetClass, baseClass, module) -> None: ...
    @staticmethod
    def load_plugin(filename, plugin_globals, plugin_locals): ...
