# mypy: disable-error-code="valid-type, name-defined, no-redef, assignment, misc, override"

from .exceptions import NoSuchClassError as NoSuchClassError, UnsupportedPropertyError as UnsupportedPropertyError
from .icon_cache import IconCache as IconCache
from .port_v2.ascii_upper import ascii_upper as ascii_upper
from _typeshed import Incomplete

logger: Incomplete
DEBUG: Incomplete
QtCore: Incomplete
QtGui: Incomplete
QtWidgets: Incomplete

def int_list(prop): ...
def float_list(prop): ...

bool_: Incomplete

def qfont_enum(v): ...
def needsWidget(func): ...

class Properties:
    factory: Incomplete
    _base_dir: str
    def __init__(self, factory, qtcore_module, qtgui_module, qtwidgets_module) -> None: ...
    def set_base_dir(self, base_dir) -> None: ...
    buddies: Incomplete
    delayed_props: Incomplete
    icon_cache: Incomplete
    def reset(self) -> None: ...
    def _pyEnumMember(self, cpp_name): ...
    def _set(self, prop): ...
    def _enum(self, prop): ...
    def _number(self, prop): ...
    _UInt = _number
    _uInt = _number
    _longLong = _number
    _uLongLong = _number
    def _double(self, prop): ...
    def _bool(self, prop): ...
    def _stringlist(self, prop): ...
    def _string(self, prop, notr: Incomplete | None = None): ...
    _char = _string
    def _cstring(self, prop): ...
    def _color(self, prop): ...
    def _point(self, prop): ...
    def _pointf(self, prop): ...
    def _rect(self, prop): ...
    def _rectf(self, prop): ...
    def _size(self, prop): ...
    def _sizef(self, prop): ...
    def _pixmap(self, prop): ...
    def _iconset(self, prop): ...
    def _url(self, prop): ...
    def _locale(self, prop): ...
    def _date(self, prop): ...
    def _datetime(self, prop): ...
    def _time(self, prop): ...
    def _gradient(self, prop): ...
    def _palette(self, prop): ...
    def _brush(self, prop): ...
    def _sizepolicy(self, prop, widget): ...
    _sizepolicy: Incomplete
    _font_attributes: Incomplete
    def _font(self, prop): ...
    def _cursor(self, prop): ...
    def _cursorShape(self, prop): ...
    def convert(self, prop, widget: Incomplete | None = None): ...
    def _getChild(self, elem_tag, elem, name, default: Incomplete | None = None): ...
    def getProperty(self, elem, name, default: Incomplete | None = None): ...
    def getAttribute(self, elem, name, default: Incomplete | None = None): ...
    def setProperties(self, widget, elem) -> None: ...
    def _delayed_property(self, widget, prop) -> None: ...
    def _setViaSetProperty(self, widget, prop) -> None: ...
    def _ignore(self, widget, prop) -> None: ...
    currentIndex = _delayed_property
    currentRow = _delayed_property
    showDropIndicator = _setViaSetProperty
    intValue = _setViaSetProperty
    value = _setViaSetProperty
    objectName = _ignore
    margin = _ignore
    leftMargin = _ignore
    topMargin = _ignore
    rightMargin = _ignore
    bottomMargin = _ignore
    spacing = _ignore
    horizontalSpacing = _ignore
    verticalSpacing = _ignore
    def tabSpacing(self, widget, prop) -> None: ...
    def buddy(self, widget, prop) -> None: ...
    def geometry(self, widget, prop) -> None: ...
    def orientation(self, widget, prop) -> None: ...
    def isWrapping(self, widget, prop) -> None: ...
    def pyuicMargins(self, widget, prop) -> None: ...
    def pyuicSpacing(self, widget, prop) -> None: ...
